version: '3'

services:
  web:
    build: .
    command: nodemon --inspect server.js
    env_file:
      - '.env'
    image: 'leodrak/express_web:latest'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
